Repository SIGMA-LA/Back-End-SIGMA-LA, pull requests merged in 2025-10, with the labels that each got.

#88 refactor: Entregas CRUD Integration
  prisma/migrations/20251005213730_add_dias_viaticos_to_entrega/migration.sql
  src/models/Empleado/empleado.controller.ts
  src/models/Empleado/empleado.routes.ts
  src/models/Empleado/empleado.service.ts
  src/models/Entrega/entrega.repository.ts
  src/models/Entrega/entrega.service.ts
  src/models/Parametro/parametro.controller.ts
  src/models/Parametro/parametro.repository.ts
  src/models/Parametro/parametro.routes.ts
  src/models/Parametro/parametro.service.ts
Labels: feature

#93 feat: add new endpoints in ordenes de produccion module
  prisma/schema.prisma
  src/models/OrdenProduccion/ordenProduccion.controller.ts
  src/models/OrdenProduccion/ordenProduccion.repository.ts
Labels: enhancement, feature, module: api, pr: ready-for-review

#98 feat: Automatiza estados de Obra y robustece flujos de pago y entrega
  package.json
  pnpm-lock.yaml
  prisma/schema.prisma
  src/models/Entrega/entrega.controller.ts
  src/models/Entrega/entrega.routes.ts
  src/models/Entrega/entrega.service.ts
  src/models/Pago/pago.service.ts
  src/models/UsoVehiculoEntrega/usoVehiculoEntrega.routes.ts
Labels: feature, module: database, pr: ready-for-review, refactor
