Repository SIGMA-LA/Back-End-SIGMA-LA, pull requests merged in 2025-09, with the labels that each got.

#18 Feature: implementar Prisma ORM
  .env.example
  .gitignore
  package.json
  pnpm-lock.yaml
  prisma/schema.prisma
  src/shared/db/prismaClient.ts
Labels: enhancement, feature, module: database, pr: ready-for-review, impact: needs-env-update

#19 Feature: Implementar migraciones en Prisma
  package.json
  prisma/migrations/20250909031923_init/migration.sql
  prisma/migrations/migration_lock.toml
Labels: feature, pr: ready-for-review

#37 Chore: Configurar hook pre push
  .husky/post-merge
  .husky/pre-push
  package.json
  src/models/Empleado/empleado.service.ts
  src/models/Vehiculo/vehiculo.service.ts
  src/shared/middlewares/errorHandler.ts
Labels: chore, pr: ready-for-review

#42 Feature/jwt authentication
  .env.example
  package.json
  pnpm-lock.yaml
  src/models/Auth/auth.controller.ts
  src/models/Auth/auth.middleware.ts
  src/models/Auth/auth.routes.ts
  src/models/Auth/auth.schemas.ts
  src/models/Auth/auth.service.ts
  src/shared/routes/index.routes.ts
Labels: feature, module: auth, pr: ready-for-review

#52 feat: create-parametro-crud
  src/models/Cliente/cliente.controller.ts
  src/models/Cliente/cliente.service.ts
  src/models/Localidad/localidad.service.ts
  src/models/Maquinaria/maquinaria.controller.ts
  src/models/Maquinaria/maquinaria.service.ts
  src/models/Parametro/parametro.controller.ts
  src/models/Parametro/parametro.service.ts
  src/models/Presupuesto/presupuesto.controller.ts
  src/models/Presupuesto/presupuesto.repository.ts
  src/models/Presupuesto/presupuesto.routes.ts
  src/models/Presupuesto/presupuesto.service.ts
  src/schemas/presupuesto.schema.ts
Labels: feature

#55 feat: refactor parametro model and related services to use cod_parametro as primary key
  prisma/migrations/20250917160733_refactor_parametro_id/migration.sql
  prisma/schema.prisma
  src/models/Parametro/parametro.controller.ts
  src/models/Parametro/parametro.repository.ts
  src/models/Parametro/parametro.routes.ts
  src/models/Parametro/parametro.service.ts
  src/schemas/parametro.schema.ts
Labels: refactor

#57 Refactor/use shared schemas package
  .npmrc
  package.json
  src/models/Cliente/cliente.routes.ts
  src/models/Empleado/empleado.routes.ts
  src/models/Localidad/localidad.routes.ts
  src/models/Maquinaria/maquinaria.routes.ts
  src/models/Obra/obra.routes.ts
  src/models/Parametro/parametro.routes.ts
  src/models/Presupuesto/presupuesto.routes.ts
  src/models/Vehiculo/vehiculo.routes.ts
  src/models/Visita/visita.routes.ts
  src/schemas/cliente.schema.ts
  src/schemas/common.schema.ts
  src/schemas/empleado.schema.ts
  src/schemas/localidad.schema.ts
  src/schemas/maquinaria.schema.ts
  src/schemas/obra.schemas.ts
  src/schemas/parametro.schema.ts
  src/schemas/presupuesto.schema.ts
  src/schemas/vehiculo.schema.ts
  src/schemas/visita.schema.ts
Labels: enhancement
